server:
  port: 8080

spring:
  application:
    name: springboot-minimal-rag-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/rag_demo
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
      embedding:
        options:
          model: nomic-embed-text:v1.5

    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 768
        table-name: vector_store_ollama

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

rag:
  knowledge-base:
    default-category: 知识
    chunk-size: 500
    chunk-overlap: 80
    default-directory: knowledge-base
    recursive-sync: true
    bootstrap-path: knowledge-base
    bootstrap-category: 知识
  retrieval:
    vector-top-k: 6
    similarity-threshold: 0.45
    keyword-top-k: 6
    trgm-similarity-threshold: 0.08
    fusion-top-k: 6
    rrf-k: 60
    query-rewrite-enabled: true
    rewrite-query-count: 2
  evaluation:
    case-file: retrieval-eval/tutorial-eval-cases.json
